# Generated by Django 6.0.3 on 2026-03-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_alter_subscription_course_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update_email_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней рассылки'),
        ),
    ]
